### PR TITLE
Rails Security Upgrade 5.2.2.1 - Payments Exercise

### PR DESCRIPTION
**Pull request by plasticwrapper**
https://www.pivotaltracker.com/story/show/164642421

### CODE REVIEW

**Comment by codebop** [comment]
LGTM

**Comment by codebop** [comment]
Donny, you should remove me from this repo. I haven't worked at the company in a long time

**Comment by plasticwrapper** [comment]
Thanks, @codebop.  I'll update the team list.  Take care!

**Comment by plasticwrapper** [comment]
Hey @codebop -- I just finished double checking... you're not explicitly defined as a team member with write access.  This is a public repo, and it looks like you're still a watcher... that's probably why you're getting these notifications, depending on your settings.

https://github.com/springleaf/payments_exercise/watchers

Feel free to let me know if you'd like help `unwatching` the repo.  It's just a little button near the top right of the repo's main page.

**Comment by codebop** [comment]
ah right its a public repo. Have a good one!

**Comment by themoffatt** [comment]
LGTM 👍

**Pull request merged**
